services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
    ports:
      - 5432:5432
    networks:
      - hotel-management-service-network
  rabbitmq:
    image: rabbitmq:3.7.25-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: test-rabbitmq-user
      RABBITMQ_DEFAULT_PASS: test-rabbitmq-password
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - hotel-management-service-network
  spring-boot-app:
    build:
      dockerfile: Dockerfile
    image: hotel-management-service:latest
    ports:
      - 8080:8080
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - hotel-management-service-network
networks:
  hotel-management-service-network:
    driver: bridge