services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
    ports:
      - 5432:5432
    networks:
      - hotel-management-service-network
  # TODO: Add the rabbitmq service
  spring-boot-app:
    build:
      dockerfile: Dockerfile
    image: hotel-management-service:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - hotel-management-service-network
networks:
  hotel-management-service-network:
    driver: bridge


