CREATE TABLE hotels
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    location    VARCHAR(255),
    total_price BIGINT,
    image_url   VARCHAR(255)
)
CREATE TABLE reviews
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating   BIGINT,
    comment  TEXT,
    hotel_id BIGINT REFERENCES hotels
);