CREATE TABLE reviews
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating   BIGINT,
    comment  TEXT,
    hotel_id uuid NOT NULL
    -- TODO: Check if a foreign-key could be better here
);