CREATE TABLE reviews
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating   BIGINT,
    comment  TEXT,
    hotel_id uuid NOT NULL,
    FOREIGN KEY (hotel_id) REFERENCES hotels (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);